import Head from "next/head";
import Container from "../components/Container";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import {
  AiFillShop,
  AiFillMoneyCollect,
  AiFillSafetyCertificate,
  AiOutlineUser,
} from "react-icons/ai";
import FAQ from "../components/FAQ";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Container>
        <div className="py-8">
          <h1 className="text-3xl font-bold text-center"> Our Features </h1>

          <div className="grid grid-cols-2 md:grid-cols-4 py-8 gap-8">
            <div className="p-6 border shadow-xl flex flex-col items-center rounded-lg overflow-hidden">
              <h2 className="font-bold text-2xl">Affordable</h2>
              <AiFillMoneyCollect className="text-darknight" size={60} />
            </div>
            <div className="p-6 border shadow-xl flex flex-col items-center rounded-lg overflow-hidden">
              <h2 className="font-bold text-2xl">Fast</h2>
              <AiFillShop className="text-darknight" size={60} />
            </div>
            <div className="p-6 border shadow-xl flex flex-col items-center rounded-lg overflow-hidden">
              <h2 className="font-bold text-2xl">Safe</h2>
              <AiFillSafetyCertificate
                className="text-darknight"
                size={60}
              />
            </div>
            <div className="p-6 border shadow-xl flex flex-col items-center rounded-lg overflow-hidden">
              <h2 className="font-bold text-2xl">User Friendly</h2>
              <AiOutlineUser className="text-darknight" size={60} />
            </div>
          </div>
        </div>
      </Container>

      <section className="min-h-screen flex flex-col justify-center items-center bg-gradient-to-tr to-indigo-600 from-darknight bg-cover bg-no-repeat bg-fixed">
        <h4 className="text-4xl text-white font-extrabold max-w-[40ch] text-center p-6 ">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora,
          autem?
        </h4>
        <AiFillShop className="text-white" size={60} />
      </section>

      <FAQ/>
    
    </main>
  );
}
