import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <main className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero container">
          <div className="hero-text">
            <h1>Shop All you Need at One Place!!</h1>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed
              eveniet natus fuga mollitia numquam adipisci quam reiciendis
              facilis non itaque.
            </p>
            <Link href="/shop" >
              <a className="cta cta-primary">Shop Now</a>
            </Link>
          </div>
          <div className="hero-image">
            <Image src="https://source.unsplash.com/400x400?shop" alt="" height="500px" width="500px" />
          </div>
      </div>

    </main>
  );
}
